name: "Install Scipion"
description: "Frees up disk space, installs dependencies, installs Miniconda, and finally Scipion"

runs:
  using: "composite"
  steps:
    - name: Set up MPI
      uses: mpi4py/setup-mpi@master
      with:
        mpi: 'openmpi'
    
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gcc g++ make cmake
