name: "Checkout to branch if exists"
description: "Clones the specified repository in the provided branches if exist"

inputs:
  repo_url:
    description: "Url to the repository to clone"
    required: true
  prioritized_branches:
    description: "List of branches to try to checkout in priority order"
    required: true
  path:
    description: "Path to download the repository into"
    required: false
    default: ${{ github.workspace }}
  target_name:
    description: "Target name for the repository to clone"
    required: false

runs:
  using: "composite"
  steps:
    - name: Get repo name
      run: echo "REPO_URL=\"${{ inputs.repo_url }}\"" >> $GITHUB_ENV

    - name: Clone repository
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        if [ -n "${{ inputs.target_name }}" ]; then
          git clone $REPO_URL ${{ inputs.target_name }}
        else
          git clone $REPO_URL
        fi
