name: Dummy workflow
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
      
      - name: Test action
        env:
          TARGET_BRANCH: ${{ github.head_ref }}
        uses: scipion-chem/.github@$TARGET_BRANCH
