name: Test clone in branch step
on:
  workflow_dispatch:
  pull_request:

jobs:
  test-clone-in-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
      
      - name: Run clone in branch step
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          target_name: "test"
          path: ${{ github.workspace }}/../
