name: Test clone in branch step
on:
  workflow_dispatch:
  pull_request:

jobs:
  test-clone-in-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
      
      - name: Run clone in branch step (changing name)
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          target_name: "test"
          path: ${{ github.workspace }}/../
          verbose: true

      - name: Setup folder for default name test
        working-directory: ${{ github.workspace }}/../
        run: mkdir default-name-test
      
      - name: Run clone in branch step (default name)
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          path: ${{ github.workspace }}/../default-name-test
          verbose: true
      
      - name: Setup folder for branch checkout test
        working-directory: ${{ github.workspace }}/../
        run: mkdir branch-checkout-test
      
      - name: Run clone in branch step (with branches)
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          path: ${{ github.workspace }}/../branch-checkout-test
          verbose: true
          prioritized_branches: "noexiste,${{ github.head_ref }},noexiste2,main"
