name: Test clone in branch step
on:
  workflow_dispatch:
  pull_request:

jobs:
  test-clone-in-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Get branch name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME=${{ github.head_ref }}
          else
            ref=${{ github.ref }}
            BRANCH_NAME=${ref#refs/heads/}
          fi
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch name: $BRANCH_NAME"
      
      - name: Run clone in branch step (changing name)
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          target_name: "test"
          path: ${{ github.workspace }}/../
          verbose: true

      - name: Setup folder for default name test
        working-directory: ${{ github.workspace }}/../
        run: mkdir default-name-test
      
      - name: Run clone in branch step (default name)
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          path: ${{ github.workspace }}/../default-name-test
          verbose: true
      
      - name: Setup folder for branch checkout test
        working-directory: ${{ github.workspace }}/../
        run: mkdir branch-checkout-test
      
      - name: Run clone in branch step (with branches)
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          path: ${{ github.workspace }}/../branch-checkout-test
          verbose: true
          prioritized_branches: "noexiste,$BRANCH_NAME,noexiste2,main"
      
      - name: Setup folder for silent branch checkout test
        working-directory: ${{ github.workspace }}/../
        run: mkdir silent-branch-checkout-test
      
      - name: Run clone in branch step (with branches non verbose)
        uses: ./.github/composites/clone-in-branch
        with:
          repo_url: $(git config --get remote.origin.url)
          path: ${{ github.workspace }}/../silent-branch-checkout-test
          prioritized_branches: "noexiste,$BRANCH_NAME,noexiste2,main"
      