name: Test install Scipion workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: scipion-chem/.github@${{ github.head_ref }}
